# ==============================================================================
# WAS AuthorizationPolicy
# ==============================================================================
# 목적: was-service 접근 제어 (Zero Trust)
#
# 보안 원칙:
# - blog-system namespace의 web pod에서만 접근 허용
# - 포트 8080만 허용
# - /api/*, /actuator/* 경로만 허용
# - 기타 모든 접근 차단 (외부 직접 접근 불가)
#
# 효과:
# - 외부 → was 직접 접근 차단
# - web → was만 허용 (프록시 패턴 강제)
# - 계층 간 우회 방지 (web → mysql 차단)
# ==============================================================================
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: was-authz
  namespace: blog-system
  labels:
    app: was
    tier: backend
spec:
  selector:
    matchLabels:
      app: was

  action: ALLOW

  rules:
  # Rule 1: blog-system namespace의 web pod에서만 접근 허용
  - from:
    - source:
        principals: ["cluster.local/ns/blog-system/sa/default"]  # ServiceAccount
        namespaces: ["blog-system"]  # blog-system namespace만
    to:
    - operation:
        ports: ["8080"]  # WAS 포트만 허용
        paths: ["/api/*", "/actuator/*"]  # API 및 모니터링 경로만
