# ==============================================================================
# PeerAuthentication (mTLS 정책)
# ==============================================================================
# 목적: Istio mesh 내부 트래픽 암호화 설정
#
# 정책:
# - 기본: STRICT (모든 mesh 내부 트래픽 mTLS 강제)
# - 예외: web-service:80만 PERMISSIVE (Nginx Ingress 호환)
#
# 효과:
# - web → was: mTLS 강제 (보안 강화)
# - Ingress → web: plain text 허용 (호환성 유지)
# - was → mysql: plain text (mysql은 mesh 제외)
#
# 참고:
# - Commit 0b8d573: STRICT → PERMISSIVE 변경 (502 에러 해결)
# - 현재: portLevelMtls로 세밀한 제어 (보안 + 호환성)
# ==============================================================================
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: blog-system
spec:
  mtls:
    mode: STRICT  # 기본은 STRICT (모든 mesh 내부 트래픽 mTLS 강제)

  # 포트별 예외 설정
  portLevelMtls:
    80:
      mode: PERMISSIVE  # web-service:80만 예외 (Nginx Ingress Controller 호환)
