# ==============================================================================
# MySQL Backup PVC
# ==============================================================================
# 용도: MySQL 백업 파일 저장 (Longhorn 스토리지)
# 정책: 7일 보관 (CronJob에서 관리)
# ==============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-pvc
  namespace: blog-system
  labels:
    app: mysql-backup
spec:
  accessModes:
    - ReadWriteOnce  # CronJob은 순차 실행 (Forbid policy)
  storageClassName: longhorn  # 클러스터 기본 StorageClass
  resources:
    requests:
      storage: 10Gi
