# ==============================================================================
# MySQL Backup CronJob
# ==============================================================================
# 스케줄: 매일 오전 3시 (KST 기준)
# 백업 방식: mysqldump → AWS S3 업로드
# 보관 정책: S3 Lifecycle (7일 후 자동 삭제)
#
# 참고: emptyDir 사용 (Job 종료 시 자동 정리, Longhorn 문제 우회)
# ==============================================================================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: blog-system
  labels:
    app: mysql-backup
spec:
  # 매일 오전 3시 (UTC 18:00 = KST 03:00)
  schedule: "0 18 * * *"
  # 동시 실행 방지
  concurrencyPolicy: Forbid
  # 실패한 Job 히스토리 보관
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      # Job 타임아웃: 30분
      activeDeadlineSeconds: 1800
      template:
        metadata:
          labels:
            app: mysql-backup
          # Istio sidecar 제외 (백업 Job에 불필요)
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          # ==============================================================
          # Init Container: MySQL Backup (mysqldump)
          # ==============================================================
          initContainers:
          - name: mysqldump
            image: mysql:8.0
            command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "=== MySQL Backup Started: $(date) ==="

              # 백업 파일명 (날짜 포함)
              BACKUP_FILE="/backup/mysql-backup-$(date +%Y%m%d-%H%M%S).sql"

              # mysqldump 실행
              echo "Creating backup: $BACKUP_FILE"
              mysqldump -h mysql-service -u root -p"$MYSQL_ROOT_PASSWORD" \
                --all-databases \
                --single-transaction \
                --quick \
                --lock-tables=false \
                > "$BACKUP_FILE"

              # 백업 파일 압축
              gzip "$BACKUP_FILE"
              echo "Compressed: ${BACKUP_FILE}.gz"

              echo "=== MySQL Dump Completed: $(date) ==="
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          # ==============================================================
          # Main Container: S3 Upload + Cleanup
          # ==============================================================
          containers:
          - name: s3-upload
            image: amazon/aws-cli:2.15.0
            command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "=== S3 Upload Started: $(date) ==="

              # 최신 백업 파일 찾기
              LATEST_BACKUP=$(ls -t /backup/mysql-backup-*.sql.gz | head -1)

              if [ -z "$LATEST_BACKUP" ]; then
                echo "ERROR: No backup file found!"
                exit 1
              fi

              echo "Uploading: $LATEST_BACKUP"

              # S3에 업로드
              aws s3 cp "$LATEST_BACKUP" "s3://${S3_BUCKET}/$(basename $LATEST_BACKUP)"

              echo "✅ Uploaded to S3: s3://${S3_BUCKET}/$(basename $LATEST_BACKUP)"

              # S3 백업 목록 (최근 5개만)
              echo "=== S3 Backups (recent 5) ==="
              aws s3 ls "s3://${S3_BUCKET}/" | tail -5

              echo "=== Backup Job Completed: $(date) ==="
            env:
            - name: S3_BUCKET
              value: "jimin-mysql-backup"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-s3-credentials
                  key: AWS_DEFAULT_REGION
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          volumes:
          - name: backup-storage
            emptyDir: {}  # Job 종료 시 자동 정리 (S3에 영구 저장)
          restartPolicy: OnFailure
