apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-dest-rule
  namespace: blog-system
spec:
  host: web-service  # Service 이름

  subsets:
  - name: stable  # 안정 버전
    labels:
      # Argo Rollouts가 자동으로 rollouts-pod-template-hash 레이블 추가
      # stable Pod에는 stable hash 레이블이 붙음

  - name: canary  # 카나리 버전
    labels:
      # canary Pod에는 canary hash 레이블이 붙음
