---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: claude-api-key
  namespace: security
spec:
  encryptedData:
    api-key: AgBXcFRxguAfqrKzOp4DepbK9way9wD5zC8JuEjOpq6gphuxIWqebSKI9gjCHgvOpWeIrru5x32KVeeZ59OX+OEYmOtg/L+eiWqgw2G+30hn3xIrTfFm/Yc9rl8Eje3Ah9intZAW0UvfilvijSpl1W2979kPFv1Awj4z8UNj6Kd1gWoNFUPvq9oAfPyKdjbeEWecZ/rrbFHdm+Rn8mKTod4BrMHGjJ41W01I701xwOOVfvAvmHJrj0XvkcX+vDNlUJTJwpzNBZCZUh27s1FDY/m+l5zVNKPy6VpRx4mxvoXMgxWyWvH0kRYjihG+2DYx4kMzYR43ZzhH5p/31rEq/ZaIZHSAkaHED8G6kcgcvlaLeJ6CgmkgOK5lxtC+r5/tUCbWDL3VX6yQ1QLrvajzyWWY6Szd0LfDF5BZf2ivhwaWgrgezvvK7+xXAlZ95L9tOQpx18jNsMaCTqKAEUSegPWegbQ32RqMraxQzXIOBwAvkRlGGVja7iIWpugQJ64kzXVv1gD2Fa+sp+DBocY5gMl+59qpvT5D5q6CGtD6u2RvQZp4qZ4rbGZx0N6VcAmKsWJZobPWNZ42X4+IgUL4AmoPDvXQxHD9Ebo7aChtMloQ754WPGs1yOQ4pqe+S2Y1CdX0axA0vXd8R6tlqenwdZITqT7ye3M10RCw21cB3Bl+XNQRE3TSQN+pinmD7heyPJ08N5D0EvvzaOFbXRBGAccWMr9KTuQxRXBOLhsj4II5sQXerjeqtb5bLzD4DWuR/QEL4IGtN8sRjJeZfdtr9DlxrOPsgT8Ijn5SO9pzlS4u+5K/NK4kI+LhsNXgntMG7ymltsqzt/DtOsowJCo=
  template:
    metadata:
      creationTimestamp: null
      name: claude-api-key
      namespace: security
