---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-url
  namespace: security
spec:
  encryptedData:
    url: AgBpQHu/eFNlB+S8XZrSdeBIE9EADcBB3zPGwnk8OPzick08KuRHHBtM2o+9zRU5TYoWqROiSn0Cj95ZJLmB5bdr+b+PYOOMxcjkgNIqt9v+nFgcxO6+33uxTaVX7M3VYqfYXd1aZZc6QVHq/+xHck6AeY/bO/j8fcUDwX/Eud8UKYvWw1ewzMtTmTnEFtZPwG3+6E3PA4iFl2Is7IaD/Qw5vO8T4EKx0LsWkC3I8k0dKmNY2imi3hhakX04AIaG099uYAtoWTYeo29eIgVSPS6arrObKaJHV4E68kS/qEIS6l+Es8ZIWf9JxIhtW5yPAfcy9oL72JHAIyV/zAuSnyzJO9b3X/rB6B13cO1g6E/MscbRUbQsvcX0f4XpghScuTm+cbNpe4EJZ0ClAOQIhC6wQmOsc4Avn3zYTWimWeGGdoAHxxz2HRtt9b7LQVw0FQE5Dr9dKurp2aX82FfZZa7tTOqsweBGtiP64YBAFNVXRLQ6Pgnw1HfAeL/sy4Qat2dbB3p0XNgfbp/btcvht3FLY9LOMS4Rs04jzSXp75dcVQsdvBUT80ouUQzS5QjljyIHJDxidPTdD8DkPeLP5LhHL1XRGiqkB0xUqb1B9N/1nNwLqmp935R/TD6zX2PI7TCJPGksABdnJM3+G4KcH1tlwhOWZW4M/udq6WrxvMst6hDupviDZycnvAAmHWdSjeI=
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-url
      namespace: security
