---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-url
  namespace: security
spec:
  encryptedData:
    url: AgChmJWd7OxH5ARGnR4KbqfgMm6wA5mZvwcrBPYfSdFHfS3s9RLVT5rXNJENmtaRnr5odOvqH7uX8BTdeqy0fvMHXQMWI9pYqg3dHWcvbA4DzpfJjvgy1cvJJaSmfGsepwLSD4Vp5cXQVtanHOSgNNWcOolYdmNXXkQeNqabew9jU0tLx8yj+dLsVNyI5XkVzppSPx5scbU7rxgWkAt5nGl9Z7k9DE9bcVSOat6E5Ei5lZE6x0oI7GHudVSnqKV4GT+ZcZgIhhGyfu5L4zIL/7lezehXEL6czFKBA6GIofdEUcNqvekP8Btk8E8IUOrYreT+ib74DbA7NbysUojpjoBDeeaef6Fv+FwXBgqa94ADKfavCrTEr2Nw8Pl5oyKpIYw5EzdScdz/ds+V5Ekig61UqU8uhG9f+Yy8gq6QPZWAIkLwgXlw6vLPN0OwzVetO8ZWm5B1j9n9WoIkHrYY7sptMXHfA0plVkVDSVlWCXs11hgeqVenKACyBzoscYjUs1NrWRTIsoVwK6nHmSBllU83m22Rotd2WAKDHmuB7E7SR+EXv3CcmDoDJGQJo1NocPlUjzwaYnwBAP73GfWuiCvXZlj+zznnqlHBA+AAp4DW91eha27r+WOFei1UaaBOKe0NRyPNxVxcirdfvpe6YOGZIptAYAA6Mmw9cJkg+s/lG/LRe7TWHD23xIxamUAE+HEMued8sPb/07hLZSxgtoSocyBA6DqyeaEBkRpenz+2d9PWDtXbZEpGhb9T8ZIWLbGAjSSjWy+K8Y+DhA6zJj2o3/XvyHrwSs+Shz6i5wV527d2gMycEw555gPETGApsSmuh47+SD5JMRxDg0F/iie6v9N+Y1w/ETVPLM3Y
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-url
      namespace: security
    type: Opaque
