# Why: ghcr.io private registry에서 이미지를 pull하기 위한 인증 정보
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: security
spec:
  encryptedData:
    .dockerconfigjson: AgA26eXH4ZUwe5Su6HK2sF6t/JXzkTXXrrz7PhTEp0or0f9E2YkA43YPpkI1bs9BlJroI3d2l8M3qukLmc0L9AQLhAEFFYEcIpLx3qyHh09q4niFFOgEzHdJ1BFOguK1qdWzxh4iqEgvfa0psSKmiFfBw84xw6rcxrwsICLSsZpUyIU0axyQb2U9bdADkv53PZFn0geMe3JHk3aYjGiLxdd73payp4zRbgGdlCfEjhNqiyQcAdSjjHx90izcIJkGrRsw3wEaaZqiyfjxrT4v89QNtRdIYLUeWWqgzcE3kw4bcXedOZ/qyLDh3GyMGJshTWN3lYJwtFsqOIgvmOf5GQsM3IBKxf08ODWMTdtVN9tWyKQnTmzzn6hoSogWLH0dakbefulUMHN9V+1lYuKOGVbWgJkXpJZtm4zhVPN95H48jlO97JjPHAaS3LPYo0lGlRIbQwDYvMB4abkWm0ocfiCLkisbdW6rdkRlsGvFBMojdo71dMaal1W9LrvyBp/MbFjuAMXANi4liRCwkyXmzdOZlP3iRTL+AN3HnB+8MfL/oi+mSxzGnCnZyYaJXvnn+58l5Iy2iK7vAe+4hLDd9SfpEsUabDoDixKfCmm4PVbxrS56iLAAQu88dRI2qwDq6C/kOZSCCW08p8AWOlLC5CxT9rJTqlbpu3QZWapWbWrJzRawOwITU7cogWX+Vif+ggPKExCH/fi/LxQUVxuj7A99xyhP6kJHiygoaVJibnN7fKYS+mzSM7wsF+zgzWGZP8ZP+G6zMQrBGHQUUP+kiWEy3+spe2DOV7fkja4DssHnZzyH6oUCuNbT7xlwarlJ9LoL3nyysN4zxv4g1wRrsThcR9BqA0FL3pfmdIQty/w60PaAe+43cXBip3PNf2r/J0CM8jYjb9ZO7v8FasP7nMvdew+HZdftArGUBpI=
  template:
    metadata:
      name: ghcr-secret
      namespace: security
    type: kubernetes.io/dockerconfigjson
