apiVersion: v2
name: my-vpa
description: Wrapper chart for Vertical Pod Autoscaler
type: application
version: 0.1.0
appVersion: "1.4.1"

dependencies:
  - name: vpa
    version: 4.10.1
    repository: https://charts.fairwinds.com/stable
