# ==============================================================================
# WEB AuthorizationPolicy
# ==============================================================================
# 목적: web-service 접근 제어
#
# 보안 전략:
# - Nginx Ingress는 mesh 외부이므로 source identity 없음
# - web 계층은 외부 접근 허용 (Ingress 역할)
# - 실제 보안은 was-authz에서 담당 (web → was만 허용)
#
# 효과:
# - 외부 → web: 허용 (Ingress 역할)
# - 내부 mesh → web: 허용 (정상 트래픽)
# - web → was: was-authz에서 엄격하게 제어
#
# 참고:
# - Nginx Ingress는 Istio mesh 외부 (source.namespaces 매치 불가)
# - notPrincipals로 mesh 내부가 아닌 요청 허용
# ==============================================================================
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-authz
  namespace: blog-system
  labels:
    app: web
    tier: frontend
spec:
  selector:
    matchLabels:
      app: web

  action: ALLOW

  rules:
  # Rule 1: 포트 80 접근 허용 (외부 Ingress + 내부 mesh)
  - to:
    - operation:
        ports: ["80"]  # HTTP 포트만 허용
