# ==============================================================================
# Grafana Datasources ConfigMap
# ==============================================================================
# 목적: Prometheus, Loki 데이터소스 설정
# 중요: uid를 명시적으로 설정하여 대시보드와 일치시킴
# ==============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      # Prometheus - 메트릭 데이터 소스
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"

      # Loki - 로그 데이터 소스
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-stack:3100
        isDefault: false
        editable: false
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceName: Prometheus
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
