---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-daily-report-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgBFVHBV9ugJCg3u7GdRwql67gvz1XYkcY8g8ck9glXah+L37ezTWvAtATUEkguXeu3EGtagG5RY2++VucyWz7Ununc6U32xlb8L1Vv7JaLYlPRhPIfgj9BthnGXtvicWKMj9KJdX9CMZA4UkJidBxDcG3MQDYndcwHuqxYXB6XI2C3S/rsUe5tvW9g26dUaAcx1dSTWc7mMk70SEokJ1fdJ9Vwc92+eo2HZrRQ7Hm9G4aESw+K7k8C2YkEMhWUm5/dFCbBAHO0N30gD7v9R2gYUYtdXg5QrnYbbYfaCPac2w8Ag7UxqqFjyfM782NfCt4wmCTDV4jmN+Iub7CfKAaPzH+VOAgymn9xiuN3zEQFQ4Q75xiw69XGT8h10A01Tq4UYcv+3LGwOzt66K1+28/Qt2XEySLNVy/c5EcqRSVtVzOGJ1Iq4Bt3EsRa9+tWkAfUW1k0lwkFY+BambvGdG7ygOXkBQWaWJuyUSrYbHrM+B5PFs/fz2UET06IjAFxvj4MPEOmMMDFDcpflm2Sq3rl1rv1ILD7mGYuVLYy23p519DEUc0IpNl59LP1QC+tWY3b8WrKUjnEEDVHBWVdDKHIXL0wha0hTKCR/S5FO1VbfOJjw7ya26UxtSYexE2hkQ+GBxEL7q7LFBT+DcZ8vVlphEVb2AVsssqE+9OBij3+MQF/nctneSKgsYH8xIfMtvRPVqLpshQMnvVo42oplvnOTTbMZP7XOV819sz3bA7RCQ+0shzd+zhBi7NfHH7nR
  template:
    metadata:
      creationTimestamp: null
      name: grafana-daily-report-token
      namespace: monitoring
