apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wlals2/k8s-manifests.git
    targetRevision: main
    path: services/blog-system
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

  # Argo Rollouts가 자동으로 관리하는 필드 무시
  ignoreDifferences:
  - group: networking.istio.io
    kind: DestinationRule
    name: web-dest-rule
    jsonPointers:
    - /spec/subsets/0/labels
    - /spec/subsets/1/labels
  - group: networking.istio.io
    kind: DestinationRule
    name: was-dest-rule
    jsonPointers:
    - /spec/subsets/0/labels
    - /spec/subsets/1/labels
