apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/wlals2/k8s-manifests.git
    targetRevision: main
    path: apps/sealed-secrets
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # kube-system은 이미 존재
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Kubernetes가 자동으로 추가하는 기본값 무시
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: sealed-secrets-controller
    jsonPointers:
    - /spec/template/spec/containers/0/env/0/valueFrom/resourceFieldRef/divisor
    - /spec/template/spec/containers/0/env/1/valueFrom/resourceFieldRef/divisor
