"""
AI Response Service - Kubernetes Client
Why: Kubernetes API를 사용하여 자동 대응 액션 실행 (Pod 격리, 삭제, IP 차단)
"""

import logging
from typing import Optional
from kubernetes import client, config
from kubernetes.client.rest import ApiException

from .config import Config

logger = logging.getLogger(__name__)


class K8sResponder:
    """
    Kubernetes 자동 대응 클라이언트

    Why: AI 분석 결과에 따라 Pod 격리, 삭제, IP 차단 등 자동 대응 수행
    """

    def __init__(self):
        """
        Initialize Kubernetes client

        Why: InClusterConfig 사용 시 Pod 내부 ServiceAccount 자동 로드
        """
        try:
            if Config.K8S_IN_CLUSTER:
                config.load_incluster_config()
                logger.info("Loaded in-cluster Kubernetes config")
            else:
                config.load_kube_config()
                logger.info("Loaded kubeconfig from local file")

            self.core_v1 = client.CoreV1Api()
            self.networking_v1 = client.NetworkingV1Api()

        except Exception as e:
            logger.error(f"Failed to initialize Kubernetes client: {e}")
            raise

    def isolate_pod(
        self, namespace: str, pod_name: str, dry_run: bool = False
    ) -> bool:
        """
        Pod 격리: NetworkPolicy를 생성하여 모든 트래픽 차단

        Args:
            namespace: Pod namespace
            pod_name: Pod name
            dry_run: True일 경우 실제 적용 없이 로그만 기록

        Returns:
            bool: 성공 여부

        Why: 악성 Pod의 네트워크 통신을 차단하여 추가 피해 방지
        """
        policy_name = f"isolate-{pod_name}"

        logger.info(
            f"{'[DRY-RUN] ' if dry_run else ''}Creating NetworkPolicy to isolate pod: {namespace}/{pod_name}"
        )

        if dry_run:
            logger.info(
                f"[DRY-RUN] Would create NetworkPolicy: {namespace}/{policy_name}"
            )
            return True

        try:
            # Get pod labels
            pod = self.core_v1.read_namespaced_pod(pod_name, namespace)
            pod_labels = pod.metadata.labels or {}

            if not pod_labels:
                logger.warning(
                    f"Pod {namespace}/{pod_name} has no labels, using name selector"
                )
                pod_labels = {"pod-name": pod_name}

            # Create NetworkPolicy
            policy = client.V1NetworkPolicy(
                metadata=client.V1ObjectMeta(
                    name=policy_name,
                    namespace=namespace,
                    labels={
                        "app": "ai-response",
                        "action": "isolate",
                        "managed-by": "ai-response-service",
                    },
                    annotations={
                        "description": f"Auto-generated by AI Response Service to isolate {pod_name}",
                    },
                ),
                spec=client.V1NetworkPolicySpec(
                    pod_selector=client.V1LabelSelector(match_labels=pod_labels),
                    policy_types=["Ingress", "Egress"],
                    # Why: 빈 배열 = 모든 트래픽 차단 (default deny)
                    ingress=[],
                    egress=[],
                ),
            )

            self.networking_v1.create_namespaced_network_policy(namespace, policy)
            logger.info(f"Successfully created NetworkPolicy: {namespace}/{policy_name}")
            return True

        except ApiException as e:
            if e.status == 409:  # Already exists
                logger.warning(
                    f"NetworkPolicy {namespace}/{policy_name} already exists"
                )
                return True
            logger.error(f"Failed to create NetworkPolicy: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error while creating NetworkPolicy: {e}")
            return False

    def delete_pod(self, namespace: str, pod_name: str, dry_run: bool = False) -> bool:
        """
        Pod 삭제: 악성 Pod를 즉시 제거

        Args:
            namespace: Pod namespace
            pod_name: Pod name
            dry_run: True일 경우 실제 적용 없이 로그만 기록

        Returns:
            bool: 성공 여부

        Why: 고위험 Pod는 즉시 제거하여 추가 공격 방지
        """
        logger.info(
            f"{'[DRY-RUN] ' if dry_run else ''}Deleting pod: {namespace}/{pod_name}"
        )

        if dry_run:
            logger.info(f"[DRY-RUN] Would delete pod: {namespace}/{pod_name}")
            return True

        try:
            self.core_v1.delete_namespaced_pod(
                name=pod_name,
                namespace=namespace,
                grace_period_seconds=0,  # Why: 즉시 종료
            )
            logger.info(f"Successfully deleted pod: {namespace}/{pod_name}")
            return True

        except ApiException as e:
            if e.status == 404:  # Not found
                logger.warning(f"Pod {namespace}/{pod_name} not found (already deleted?)")
                return True
            logger.error(f"Failed to delete pod: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error while deleting pod: {e}")
            return False

    def block_ip(
        self, namespace: str, pod_name: str, ip_address: str, dry_run: bool = False
    ) -> bool:
        """
        IP 차단: Cilium NetworkPolicy를 생성하여 특정 IP 차단

        Args:
            namespace: Target namespace
            pod_name: Target pod name
            ip_address: IP address to block
            dry_run: True일 경우 실제 적용 없이 로그만 기록

        Returns:
            bool: 성공 여부

        Why: 공격자 IP를 차단하여 추가 공격 방지
        Note: Cilium NetworkPolicy는 CustomResource이므로 별도 API 필요
        """
        logger.warning(
            f"{'[DRY-RUN] ' if dry_run else ''}IP blocking requested but not implemented yet: {ip_address}"
        )
        logger.info(
            "To implement: Use Cilium CRD (CiliumNetworkPolicy) or Kubernetes NetworkPolicy with CIDR"
        )

        # TODO: Implement Cilium NetworkPolicy
        # - Custom Resource Definition (CRD) 사용
        # - kubernetes.client.CustomObjectsApi 필요
        # - Cilium CRD 스키마에 맞춰 생성

        return False

    def get_pod_info(self, namespace: str, pod_name: str) -> Optional[dict]:
        """
        Get pod information

        Args:
            namespace: Pod namespace
            pod_name: Pod name

        Returns:
            dict: Pod info (labels, status, etc.) or None if not found
        """
        try:
            pod = self.core_v1.read_namespaced_pod(pod_name, namespace)
            return {
                "name": pod.metadata.name,
                "namespace": pod.metadata.namespace,
                "labels": pod.metadata.labels,
                "status": pod.status.phase,
                "pod_ip": pod.status.pod_ip,
                "node_name": pod.spec.node_name,
            }
        except ApiException as e:
            logger.error(f"Failed to get pod info: {e}")
            return None
