apiVersion: v2
name: my-trivy-operator
description: Wrapper chart for trivy-operator vulnerability scanning
type: application
version: 0.1.0
appVersion: "0.30.1"

dependencies:
  - name: trivy-operator
    version: "0.32.1"
    repository: https://aquasecurity.github.io/helm-charts/