---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: backup-system
spec:
  encryptedData:
    .dockerconfigjson: AgBfMq7mYFbp5g6ps2prHy/Pnxo37KZSRglxGf4csnQ9T+Y3z6ShouKDRolE+kAba4CtocBWC+t3nhFWY7jotQKtg10U9LwFZQ5amBIcM9mOJD+cdX326FKYfryJysgQ4EU0RaZE63qb9pBc68Mh9abqTmWkk8UGm3qQwO4A+SgdWV3lhid0gXV2FxBr2oqj466DZK6XTQq3wy6EOrVBFrrZbFrX8jJ21amtaEKZ2tF0JCt3q4dk0lXR8SeaU4if8B+Fay7/9qJxle/MEdtCBC7GZGEuKoo8EQaAZG1nol+zHtFYYvv9IupwzQ9lpfqDUyJIYjRltHxa8YYXBOa3WVlk4tM+/pmRgu/lzOPe2wQtkcv80XJ9EEbRMvP/k25UKfdguObNhC+I/MD8samuAyKPIcGGx+xkRZMRhdEdvyt1T0l/KSMK94kMDTma7b0tzvMUqxpevzX1eJjfShuABTPCGVWbd7iQh59Oeii74tHtCsj+roq408NJSZxHyHg7yxGg2hnaWt1Ex4N7l33XGJ4R7sHFDSkOslRGekrXTTzwxYxlZrAmRJhdKfbI6i3TOoLwWBRkxOGyC4B/qeAd/iKbOyDTazpKa+b0TgDA/3PX7c3y1zX/WgVlS2w18MffKpvyIDn4XwhDOZ2qe0rmYmJu39LehfNuGrvTVRs+lD79wgQ0/tEuqCb/f80wKfhUfs/r1YdiLQo0ZBepKMAbIYUOxBmcYMYxUODnYwBNJ54FgfAQz3EAiqqwf+89qOw2U/44khyyi9A8+Kh9/LnQVY4OawZJbEatntPmVgfV8ryIImMk9gr2vza8Keski/EgeLGUXMsYsTjTSkeChPoqlYm2z/68yImWEmbQMq2vDHEMRn4tXRFcpzI2aBS/THq2CgyLCCtTQ1+6KAaOGWVX68z8MJRbd1If8X6fYsM=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: backup-system
    type: kubernetes.io/dockerconfigjson
