---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: indexer-cred
  namespace: security
spec:
  encryptedData:
    password: AgBmKl6G6KDGL9o9R1OfCWf09penHGH0qeikgX9RNFlhTrJW+cN1OWq5UwqjGIjuA87JgD3qrq/lmAA5tAtWKyaI4tIEWlPrWX8NmNBPf7XLu5DiQ/OdV5YyLxvzley7ewARZdco1sgEnyyvTUpPd1igul56YKSo+ZAMqs+pOUPLQMHd0MYylhd6X0aSB/UeodC+loackUXl1ATZo9vjcYkN/lm9JPlG/nwBIWWb3D1jRqcz6ZmHgcodIMk3XaWemuCrF+//9T3Kx45SU/Ul+sivTIEV5RedqqYaqkFzMSLudd3YrTUEMhyTv2gupP3QiMmjzPL6zZX8wDFUnvAMaJsE32XDHRAj0zq6Nuk/oY5zaeJ/IOACmwyjQeKszHQFx870/5lAx08tR3MpivZc82eL9akYVC0G/QF5WbCgD6QWrT7x7C8E5islj1SE2832EcsSQ/HbG/JPsrR6Wl4cpIg0FPGwD+lgOFGAvkuamIgb9lktJCq5gc4cW01MHO5QVmOC6IJz1HQNaDeOItlBZjyEtKSqoMum2CefOG80yo8h5H/ahD1o21jO4KJgt9buNIOZdnM0IEMLM9ROjmLU0f8DpZ1UHAHT6izJM/OOtRcgYHMVdS8iB3lkaYuCoRmQlyruItQYkO+iVmAAunEoXsmQOo6ujy206SFU4V4KjJnC/AdNZUlcCU6Pz71zonQDYnKin+n3jYxlDgvTlGQP7A==
    username: AgCRARKSA2mVT3xC2QE+lp4iia0wKt4HnlkgSjhMKUn7aYxGa29I/4M2RFtrDhfLs3VO9EEZ09Ez3vbKw0IQ7kMZG2bZWHWwq0ugZjURTa7b2PRtRDbFUi67+M35nvAMIYKoonJANwwdmUxD2XC6fF0fVanVe5AjjDUR9rUrrKIPfKpXuiFt1VzHu/9GNRu8U2NChoN5YCHGJ4eZ7/GHlq9p8c4MiDuiMgXvef5O8tbqPNuw2/AF1I+jhx8PPXSXPk8K/HTl4TVOA02aybo2sJ+OQN1RE03VIGX78pyFtSsctnxaN9UbeC9kXysKTSObNaI8n1yLBFcij2wr0uukyzEmyerFeeUO+iAhDKoqrBcE354LPjhxLvsqfEltENF51d2RteyZYH+KJtN8r7dmZkr5xNESyzefp5ZIUGGp/bM8r5E02QIc/DXD0ec6+WhcMXQ4RL8vC6N2RY2eCwlhoGnWXF7rAU7ppWFnnv0OctzKA2JOcg00ZvpHatoYGTGoXCh8Nx/M/M932g5HDXdUwdEBtHuVCk6VWYS7RILT3LMjneodx0AMFEdWJinEukKxolhGWBbkz487LNOOG/9dHFQK3h1GDQQE0Nv+aBZZKyqStOYgHU9rIre1sRmsrGvXo6rX38gLIFmIDw97bgoL3prP9tqRl22FEp8Zn8bHK+4E9a15N/ctHF8ZgokfJCPhHKe+FHnnmQ==
  template:
    metadata:
      creationTimestamp: null
      name: indexer-cred
      namespace: security
