---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: indexer-cred
  namespace: default
spec:
  encryptedData:
    password: AgBhkNQ3X2eJchDKhRw6iYnlu5W86cQdL1lRX6vZJa6R0+rOZl1ihpLgy9Zw3GBSIR9rUg8eDN64C+Lh7vS7obWVYXjgRBvKF1a2gzBjpsMYkh/9/aie8wY00UlOhHPpxRVthCVajNegQi+9KiBUTbJUlZiJ9zLg/eNPBkBawvndfXJow3YuI34lvldq2X+x+CcR9AgYcUcgC+VgY0JSbs0S5z6QWfC67NmG2YBLWya7MAe5j116+L0zFR5dwvTdD6Nu2haMyGBJW/rL80HALlrhrdJ7mIPnMA/yMo6VoyP7W/4NIkSm4tiU5UEwn5djxlrwACtgSY3w+xLUb24D8UcFN5aTLIT98IVrWd9brTJxllLcPSgZQRMTaz4KbDKRHrht9ogLWXpoOGCrNZczKo6uWCn4wHMXKta/TgHRfpkAmAUvWSgdB8Uv+EwuSTxzUnlTm4DQkuCh6CsqaGVBmzWFG/PHKuO48B3S4wKXu4NGIB7HrCINcur/mflliCYxYiGbPs8eWQNJFb8+yG4x6FnZuwCtdC89t5X6JdTWmy+EnEQOuH2uGpivwoAUs9aehLu8SAQugGix4MKMK/vWXkAxH5TwNbhVNwsKqKag/y8unJW0hajvFLyUvkY+rbA7+wpVZ/4UMmJ7r8BjSMfsQF2iFM4acAKRXf21d1HUovObgzdzpJ5z/IXBLMmndRYZIClCgFzyi0m9/baXYudYQQ==
    username: AgAgTzeRWmjaUquBYGOoniflqBCS+Za+tVP5odyDxcsdhaD9dXSwRhwI3Zb33QqvpiJnVRScvfzca1Gm2L0ckRCotdG1niwwQ6zOdtywBIhebBMib9akyixPCKwLqdlED9jrqpT0fiVzxw4OB2ok1VHBZYwo0LQDruQLGmaMNlkmxogSepAeMQeKX92oRAbcNkcZBLEFru58s0IlR5Q98szz1a+rqFCG+3WFUlFcAo1P9/uD4hmKpp6I0j7uALsxgFPteedS2KUqOfteEm7hCHrBYRF7glSt7YdF2cxT7EiaCuX0oy/7WmIxy9u8NKxASLmihZpXLbWU66RaX88Xn+r9OF91qUh8+QApHjUiOfx5UN2U3jyHGmxJqnocV2yw4G55lBFCYqeZqVmpWsGt+Szu+USYakCFYBIg+TjYkWL7Md73Vk1R0vthDtIZg9iGaTjeWfxQSLLYgfV2d1QlmqOF8XOvV0J2Bb0IXE9sWKrFA7FaT9pgP6Pqw/NrdGqdfLWurzKmsMDceDP4iuhTbkeJ7dUUapj5h+vRU6XA1uIvLhWgbxUmUfvCt/dwwui+UbdRJIXkrIc6ldlLuv+OIOnA1rBZlxEyLWs1O4XElCv0ABkIWmWpZ5nfGeR+o3QRMRH4ovXBQySkcK5K6MLAWBHgUButz5jkt8ViTkcsgIyJLebCJhKrSDf0wYxWjhsOyEdXaJZeew==
  template:
    metadata:
      creationTimestamp: null
      name: indexer-cred
      namespace: default
