---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  encryptedData:
    key: AgAwB/mkLRRbcazkK22MB9xDUvM4YmzOb77ZX72IJuRI9WbaKcxNIHUI7KpDv4GNYoJjHVY3NPY0HXZpAejHRCUOf8HpMutJVrB4/keSyvZ9tQb4HrhdwiiDhLB2I8fgt/TAjJo5QzfS4QjOekntlIIoGXijavsUstcXsASMqjbjNg2Cit6/qjlBnh3Ib7Fgl0P3cq7efxFb3YSPeyXOc80mWPLun8vHbfdM5YPeqAXsE6CbJJy9Ueb3YqlxC3opc0+r71BoNZVo0K4N0JQIJVDq+OaXADIW4bh8pAgURS5XRRC+QLYORjB5dErHqAFWeCONhTJfdgW6sgnYQOXG1myAvI305zAUADZDlV3ZLSsPGBZd39w2sVH2RQjmfVCIaY1x9mKcE+D+u3kRYx6T+pSFwUzh9GRgOhPiDo8LWzGiXUp+nF1I2v7jH4yrl0fe9RXxcd6TlP9VnWfpihRgP6NOqzbBMoNMrOh7AdjTHCP48OUtvv73dplvhz4q9AG5KiKIZ59W69yYfSTlD9H+8y0qJ4k7diYtUYvRt9oDPjEL+D32SqhKEN97fHJFA3eJjgacPrpcwh/JDfIePVoNYS3HZ7KsMIi36j3uMdmLqIeyqcZctPqBjD4q2YVAcdicxNBdoYXwS4hlotCjIvYeymH17CymHjaE18PvhIrDL80Z+WoXDyfg9jl/SFR/P3Z+BKVBbyrKT39Top8ks7s+XUEOm5tJeuNmj0iZdKz7X6Q8RA==
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-cluster-key
      namespace: wazuh
