---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  encryptedData:
    authd.pass: AgBk7bFHLOsZtXK7UK8QpTUwhAUHuZdlcad8txHNBdY3EQnfFOlaYQ8qSbf8ugNxetkc9tc2LyMGeDWplHLlT5SOuNrkEADLkng9csVlIaz8m/4H9xgH/ZlL4VcQIlx0FQ5c4OEoCzmifBjLx0RfJN0Yxc0nX8TEY9J4Xkq1m6zsiQleFQBQelIVu44WShgMI1aeW522/iCWh9KE1eSI7oefuksyQb4VgiVwc/pzyMFucgkxIJeTSQryBfWubqLKMioauVYnWkd6Z9EmlSNI2Bymdg2JEuSPSfAE3+2t8GeONWHtjFRNSeZKGVEtt4u3Akq5baZnLkZqgQDhD9K7Lt8B4DTgStcc246sZsNQZc4MZd9pLG7tcspcgrYX02LW7Ldji5YGnDI20IAmK+zgqOBu6gqTYUkqwssX/b/L8drINOw7DhhAHTMQEGg6G/zgJeJS07G9So1TR3dIFhw1xshtCcRNX7o8B5B0eX502I8q1khmEHMn8lBc4ODq8VrZUbseb0x+MrbnnwZTYWMDBCD6VgvFHK0IT1H2FxApAEAAXyINlpaZN+W3wYDkHR0FPEOLK9HcQn2oZI/nvQptVLrVhzp5wunh1TR3jIjcaWZr4zfZNeSGp377oQxb4tuSPg89LnZ4u4or7pGjqKtSACkLr7ugsPItI8n+i3xKdeSs0K4cNPLR7p7bHXOZTwaJNrAyXp6l++xFxQ==
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-authd-pass
      namespace: wazuh
