---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-api-cred
  namespace: security
spec:
  encryptedData:
    password: AgBbJMUUGPpcwScivivHOL2EPN/RvhuxCw7avHiuDjL4XGu3w9Fws/B6mkqY9uBKBoVbmnFnXgra6JzIUnPtE4iWlagCzxS69fvOlq1SbOKXn8YjCrYtb7+I8XrLCbcOKeffFhz/y0MVqBOsYfx2EO4/JKIWnLijiVwk0wZWTCCpLJ+H84DSgHZyQPAnYXxHNJI7N30dAveBShxp24M1ovo751EY1IFfzywwUJnnicna/5B7AsHC0lPfdgMYX8iVRuhP3J6gdVWunGSxIoWALT1ngLsehhA6jbvZW9GFtM8vhht1o6WUuLyz0MUUeLuEma4uUzbKUlA3p+ae+qpbW8rXAQtYeQ+QVLaZQth+JgbZLzFYjdvowJDf9mesWX8g8wjJohScfmoBx2V9uBCSK9rCvoKy2+oM4iYsS2WZdUADDI7bPo76Adhw/6Ef2Ar8kDgCK7y4+UAmroM6NNwVHo6EAchld4TaLLwBSUrGPrHyI+3g1lyeyEkmKnRh2UEkJWoKTgX57bQnclCNteUmNbuVr9SAPX4A6RwJtogJN4E2xFVUEyf1mRdFTzdogxjzHo6wrU1lx67qJGt9CO+xT0oyRnmgTu2PPow4j6tb9rnsnIdpbrEfScr+ja3nXouCGyp92NV2gXjNbCm38do+cZZgMSwyDRPZQEIf0CymOD5a1fWyz3JQEmHgdrZv+TANs3pUTqd572ogOCwbfG5o5T0x
    username: AgBU8wti4j3wMvfIE493XdGCqagX0TxKPfs5RvtC0x+GFToyI5RBs/fu5EK6Y2NEnQMbGa5YlUHkwv9t0czdWoOkVy+C5JBcaDh/FOad5Ii2hcpSHxLKUjMzRnXTdRUap74t5gj7Uh5JColYN4l1ETe1X8CtxEfsdhx7+13OPvCivO2pSCPtqAWSMzDfQgC5OaCJAU3w2cHrlT06GwpMu6ByLNXBAh9FbrP+8Wj3ZgQMw57GGdUFrJkvPb3cEVnz7CFRk4b8DO2vPbp2UF3Xn+P2lG/FVEBum0hVf4goQqlPOaFaCRQ44sFeMsjuexLBwu6rlXD9v+GuTjWSpd4IGBm34gb3tVIKysNgR3yLvxKY+oKsLYiSAFQ888ZnPe8rEfq5RsKwFaQTWxhvFxbs7qdI1Y7pjqhJuRCBf2+xS9N5jFoqvd1mTCnp2rf+jDJEZpLRBApASAYQOY3zzoY70D6TNUMcdn4BgJET+sFKWAnLfC+TlVdjLKPsseoJWQSGdtJTBQzgEC0NuTsDwssu+OWsb/eqFKO6VLKeUP88zwZbBID/Xgamfn7t3oUQ4Y4SituSzWjsxrj/cs01qe9+tyxFRDCuj6aSBOL4D6giEoER5NmtnQ0YZai5b8t/3UjdZoLkwMCF7qYjIeYASBHzX4KiSQpUBEI4X1wLLorttEOet8zzRhFBdRse9EVgozNjuK2yRIa94fOrPvU=
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-api-cred
      namespace: security
