---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-authd-pass
  namespace: security
spec:
  encryptedData:
    authd.pass: AgAKRcGS1q30lZIRD+ysqxQqC3iJM2DKAzV0RiH6kX8HEY+lNw5G2smxxTLFGdR4F7iSqbCckrKFc/2v2FUOm8UXUugaP7dwiLJL7oIPBcrpt+vcwvRLHlLErHWc2nqTFC2KZLQ+KKACus4MSrF8GgLJUFm/yzfR7TO8tzi0+ziFGggF/q9ZlEKU4jXRC0jYP/S9qe4zai4YQ6CUnjiSlwZR4IAR6p1I+xvKHchKQmMNevqqFugw7HjVafAYECAxqTDpj7eYGr4cq/CzLEG3JwJ6q517bdwR3J5KcfV5Z71qdpMOzYGKJ0YLus5+dfD/meTX3IYUG2kZPzz0aPM4VxkqlptjxibXzRZzy3G96siMkDz2BAvySUJD2bNfMW9EVVFzINr4fDoarRyllvrzeFaW0WvfWfl8BQ3hBlF2mVkHAnvrwmJssXtWewQkXXHInNa+3WmCFVnO9tLt9mxTx7T13fD39UZYnhyxCvZwSVwTd7gPFp1A/BjZnkEw3Qbe1pegVUev8/ZkNpW2JBg9y8KtH+ARs8YSK8EJmPVRRoZfrfrbCsfA/dnkL/qCXb2p2+kANk8Hqg/WTgbLmTKC8tgSeZjCRg7TDExOgvNVvhfXjN+eSoenFxj7HqQpJ74jb34C8ByP4dFIoclQMZ19HXthk5BgfwelQ86wd3s2an824C+8qwA2siRP6HGFhOot72e21xrREr+J3g==
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-authd-pass
      namespace: security
