---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-api-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgAndHPwyTaX0Kyarc1nUV64PIFx2oa5XfagSXWRv2t/v/A7meYOXhqfI//Di8MSa/ykyl4ZS9c0t5BarqwNZUXCXBVG5kNAYVI+ecR7Pyn/+7E5V06O5qxBhV0I8qywbwUFto8HlaVTlnoGIYiCv6UBPlAiW2PqK5Hse41uW08u+AvfUyCmRruRyGVPnMhGU2Fh3ItJKfqNN5zi1kMU6rjO0Ue85tqi3UJPYNLE8KHM6YW1QnFE6+qDuN4wNNxLaB5hkvStRimSFzyUzHWJXc6ba8yLaw8kv1H4JNvwj6jVtGk/pMYAyV3C03ydDjSmAUk54L771COj4z0pT9cN1LZYwmyZesmcD/EY5Q/HinQqPabLrhDQaqoLfdbpiIkh7EYsVRCPz99z2BkvFWdIbFW5OoTcWJNXG/BNSKI068oNFGo08qAyJ8ckcTkPs4UkhNwk3RBNr90eUhMCAe+BJRXoVa5OiS2Ao8xY1mO4LfEvhvmVdXr+X0xfJskivtguHB9rAbhfz/IfO+4W38lezKLdfsbC6LIMIa59Yw508bWt6lmGP3Uk8kwLxSBIRnpJiFXI6an3BnGFkF1fw6XuqYWgEOQBPBMk+krHsZEkCJLNMEd2pXMisl6k/oFK4qpXolesm/tjXY/GMOZWC/d9VCvckY5QUfZumqysGlOkiNh311jhbaf5mmXjhxyB8rto3yPx628F6YmLYiHmOTbdi6+h
    username: AgAbPSIXJ/Yx/5FpNNFLPNP/46DXr+PbUzoFwXkRAGCxSwJdb/W5QWvBtkmxSWadw7gUli5b88/IzhwsSkL3I3qNZ9VUs58ws31LreLPjuiDi2ZL7nQczPucl6nr/+6R0Fq1zSu2Cp/n8CZ28n+KRJZfC3w/0OnrnDlGUYUxqDUCXT2k/A6MaACALl1E9bwtpV90EwB+LIjPsSfrdmCoA4EtlWp1gBfyHIBJXbMBE02JEh4h/BVk9UcVt36hDevPkeMi6A0Mjb2Tqz4DP0jK5kybx/tBeAPrJcE7AgEXqE2cklMEarhqZjtSi4vufP8L8bKhKHWrHOALJ46tEtVnZGK/CI7taiUnU2Klu1+Xa8iFjORH59OrhlhKPpKq8HajuFM1Ywd2pFEJMcx/xpZmUthgYjACwn6nlrTTeEg6o+ObWlQ0JHDZ1FJfOeBzFHKiUcolml7LjaNfUzXArgQZ5DPPQe08CroFh78FzF4eEL3S0UDhLBbe5rNM26jaZ7RlXW0rofxNFlODkwSsdLVlnv3yE1+PCY/2wUCgm/uH6Q78KbYxNfGJv/3VXUCUzkvAzet/zBw7ixaFnqJjoLboJbIS2ihhucVGeEvMNiCNxH3AgeNp0fd0QNuZmGLByxyAdB9S3uMk/2150zVPNVymuIVlxs6A5mcA5SoUXwjm9wi2UWdP+T6OtV6AA9WsdOJyMZz4GIQ5WKZWOEk=
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-api-cred
      namespace: wazuh
