---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  encryptedData:
    key: AgA6Qb19b8JPyPHaJ12J5Q++if/+L/G7WpSEivploJYprD5+DhHVkRRxULjlPcWz8yXVdnGoly2kZHnn68Gkb0/2O9mq9eT1w4QMY+IwFolkZcjmhFWQR0nCFm2kgzji4e03RfeGV0sAlJboYFVtKRlTBSb8/9wOjZGgVK6BsPPy+/GOCvGj6aIUjfOI2dOwdmX7gdlG5nlubDkGmH9WMC+yYC8/Gm+kqQVYNQ8tHnvodoH0tw2YwaoPJfeJMnlUSYEJ2UM9jOVqfuVhEDt1HpQVYkbT6l5ryPNxSdLv0n7yMlAzbdrUYUz6R7o4btJhiMHM2IOhnNF+d/+I/K6mqYgPsih3E1rflq5fqL12vnyzCjZ80VZ6TcQ9IvgNMyKplGVGaibmQoludiuoucsLjZ9qXJ+vuWMrbUEP1OH/yxmlzEqB+0DF+hfjfVhPhON96HDJfKiLsQuUsDFzBmHA2KwW04i59XvfheJGdrtbVyBS34ABYufBEtiCCf63P8GDGDUdXn3JxM1Vl55SwoJ8BDzK7x8zvnkKMGSKNFK5Kq7S077xF55cHysN6ftfZdPdWwGSQesTYgReb4DEH4fYbaBDg6nNNab/oDHNF1+u20X99o0WHt/5W8A6ezitW5tEg/QiQZB+W+RFlXeEMUb/cCJTdvERgvjL8FzfCXPlcWT2zKYTy9psjojO7HNmzEp15+1OgbYDzc8jiO+FBRsSbFiGIkpi6AIOQLmHexEQF7VMyw==
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-cluster-key
      namespace: wazuh
