---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-api-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgA3GqvJUID7f+hno8jbaDbnku2SGKiEQn0OzAknWYcqBPyxuncCI1LXPstEa0CWcuryjKi9NVaDbfHTBo1HWrvEFKM/a7uEtOpC9VgdxOlOpkQJzQjTTcriGnZkcWTww+zfQL2ILTacY175iciIGXYZVo8KbY1kWPOt6jHvCENaVrIsZDs1hfXnxH40FB+0MdYd57guP8jxFLxWWkZgNN/AS6VM1rTbhltmrOwoHTW1lManfqG4X4Daj7ejBE1Bhp6b53PARaSjqf3rux2Ij+ILhq0WjhS18euvW+nnJ87Qy0i1jamQdqIgd1mqbp0GDVWPdT0QjiqBK8vzPcBiVW3rQ9oAJC/qiE5fOZEBJ6kD9dXaWH9LotdRUvhAroBwE1knDgbCQqIikIiKjakW67dCwQb6BGBEYjq3in96aalA2OUV0dybPQ1GpscjCaLIETk8aFKqxH8VDCemIjqfVNefWFWAmnE0qAiYpiPtLFZmSKn79rdfMhuQ0SoFCJoanjRRohz4IBaMOlW+YmQL2EHj1yUm2vWTNfBnxPniFG/1KylrhbroNJD1NpFcyblFD3KZd8jWzYAFWzSuQ1MuprUvsSHBkVjVuxisr9Yv+I75mWpJuRuocRFMMb+mflFvLehqaVY+rbXc6erZ0BR5/BdnWGq0XeRNHhAwzACP5NtDn7rhlnqTwKlTkfSbtkLZE/LDAcoE7/O5P2I/KeGe5rlF
    username: AgBZpEQEPTtvT0LYwMS6lQrSkuts7T7ExLabvB8RGCXR+brgR4UTXcAZH6hyOVB+iN27vLbn/Rcz9dE6lBs9HTG3pCQVagoAj6r4s1eY6edBSXHyQ4daRpdFq3YYfnQ9zcP9hi1OsrLf9/BzfV8ArhznQjMhXTuxqK5aetcc3k9HQwZ1x95Bvv4QCGa1D7syLc9GHbsze2B3k7JcMxBTssaXX/9575ZVDUtst1MJxol6ZaFf/9dvYXoxl2yJRtkcfCSRC550reOcwjuyJy3we0LyE/v0ejxoHPtN9HTvvIljI/9zXSKaLGS2tGwEzynbhjx34HW3xQmSdUT22VtukiEr0KJFFKsPb83OAlnn87IjpylUo1L4cQeU1n2iD2KMuRgsPGfHE0bjf/uE+8AmW8Vk0ebcL2qDPjW+2IhOQ/yXsyaqBp1FmVcI3X7Zw3euwBKFv4jBHn3Zbv5sbC9jIR/iRlxyviHxDuSDabC9yPWIBCpvclJrGi/8wr5hySdhpP57sFScScbyTyJ/puFiDBCLE/xksL6uMSfgc6dVlvdip58UlzzmyKmsj5H42ohsfi86g0gBX9eoWV6O0p+ix+oYV0i+hybxg118jBn3UjHS6/5UT0Hf52ILOk1/cYcXjonTsMbnzmowsV3YMrWe0+1ISvBrE557Okt2PqFtbZfmsbvBgPVFUw73Lxwiz7tuD8XGIGq34XJEtgA=
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-api-cred
      namespace: wazuh
