---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-authd-pass
  namespace: security
spec:
  encryptedData:
    authd.pass: AgBMOsy5ehDrniivZsGcb4Pxh1A7EbZFO37NbBW5PESEr1esDnoQthJjAfmU/Tv7nS9aBNgR/exD0U1cxshsQrWbSNTNiQd1LILpP0gIutkAXG6Z3SsqU0WNz1hm37g2wNeGJSw7FUvM4VsTijA4YOksyP8Kb88NZ0U0Q5nKVk7h9js58Ik0EkQUo6m0QVE+sIdpDvpJcq3HC+NzAmCu5appUly6UOMA+ddUvhWpDbNvmBX+W7N2b1Kj3OqWgxcu6d5liiH8CronebTa8yfKBg1EUay6yZAYF4gzoccV80wEJYhC930SekPEB/VPNIQq49iWVRvu1nEaya0hdgYhs95R0A54S74odxZuGcNcbDdD1UITwIzCaCM8ZY2kB0rH+7CmSV8SAUsGK5X32PiXwhujLtocOZSlXXdvHHEzj6BCgA87Rg9a2IGeXREEigID2YUTTLVRnGyFaQYUmFBaoRzAMN1KujtKbEkeMKB+JvaZQHMowC8gIYz+uDGVmaB8JUF+uIIlHzhMUg60zZji3qkttYYDju15LvidOquFNAPAGytSAHEJFR7Q2jlcZSbwxws2e30nWqVCaAsBFZ9sBHPtN30dbJFAo8AYc8o7GgYqBT9PPryvpcgr/2LfxLseDsRN7A0aKGfpXYhZMzWZxBUwiq8tgTXkzdBShii4mIDrH5Hy0qmomVITzIi9Vyb5yt4t8JBYG9Irwg==
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-authd-pass
      namespace: security
