---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  encryptedData:
    key: AgAVFxEkUmf6QHKPYqlZHASWkARNtI56EJf8ZPm9IHv5N86QKvKBE0SQ8W4ON7sXkrfYkEbzQuA+YtMbz03yF9TdNtKuMm5w98su+K6sLh/L20UEc4JOGgpblKlg6o8hcrhQJvnL3kzLi1nfXkKvBbqDwYT5GZhmVIFa0mhKxADFv1FokAHm+KJJ6qgSfAD5JELlGgjgJNck/ip3aojliAO/MQ7hyY7RonNUk3G7oG9MmuWb3xmnWD9MswcTy5UFyO4SuFGblstRoBprjxrpNLjB+Hb76z7yzdVeO/kk5sNOjeFumkaponWtnsTvNGVeIDxkiGwU6QLYU67oSIzHNeIDBTICLzArLzcZFHxxVWUo88OYLZS35ezRb1GWI6b49TiiD2uR8wwg+IC6cDyQ3drNBR078QIW5A55lNybtLR7aQTiA7nv5UTEfOGDwuEnUMJRbMV/zbaQEP63agRiLOyrZBngys/tRJyRAJ6R9uP63DoK3ZEtErt/14+KAJAq1ZRFy2yUwt8n4nOwK6CankMa6owrQxQqfHzIDlsSiQW1C9pS0Z5KoV6IG7/Unml/jc46jQzvLZIATZeRhyMdSMeL2J89mTy2KP724fM3HQaq9DgWgwByt+N27YbOVQwTnEBnDBL56Ph0YmZ8Eu5m/T2UCeaKtulL72fpoDoY4bQAVWtNTpW2IRD74l5nNojE9zGify6gGB9XOcwWqc8GdrN1oRs5/IiV8RlZ5ulNftEH9A==
  template:
    metadata:
      creationTimestamp: null
      name: wazuh-cluster-key
      namespace: wazuh
